# From rules to floorplan

Date: 19-10-2021
Author: Marnix van den Assum

This code is made to go from written rules to a configuration. In the first part libraries are imported, a grid is made and the canals are added manually. Later the roads are added and wells are placed.

## 1. Import libraries

In [318]:
# importing NumPy for using matrices
import numpy as np

# importing Pandas and display for clearer representation of table data and matrices
import pandas as pd
from IPython.display import display

## 2.1 Define grid size

In [319]:
# Define the grid size
len_vertical = 14
len_horizontal = 24

## 2.2 Canals

In [320]:
# The canals are manual input as a list of coordinates

stream_1= [
    
    (0, 12),
    (1, 12),
    (2, 12),
    (3, 12),

    (4, 12),
    (4, 11),
    (4, 10),
    (4, 9),
    (4, 8),
    (4, 7),
    (4, 6),

    (4, 5),
    (5, 5),
    (6, 5),
    (7, 5),
    (8, 5),
    (9, 5),
    (10, 5),
    (11, 5),
    (12, 5),
    (13, 5),
]

stream_2 = [

    (10, 6),
    (10, 7),
    (10, 8),
    (10, 9),
    (10, 10),
    (10, 11),
    (10, 12),
    (10, 13),
    (10, 14),
    (10, 15),
    (10, 16),
    (10, 17),
    (10, 18),
    (10, 19),
    (10, 20),
    (10, 21),
    (10, 22),
    (10, 23),
] 

# Combine the streams
water = (stream_1 + stream_2)

print(water)

[(0, 12), (1, 12), (2, 12), (3, 12), (4, 12), (4, 11), (4, 10), (4, 9), (4, 8), (4, 7), (4, 6), (4, 5), (5, 5), (6, 5), (7, 5), (8, 5), (9, 5), (10, 5), (11, 5), (12, 5), (13, 5), (10, 6), (10, 7), (10, 8), (10, 9), (10, 10), (10, 11), (10, 12), (10, 13), (10, 14), (10, 15), (10, 16), (10, 17), (10, 18), (10, 19), (10, 20), (10, 21), (10, 22), (10, 23)]


## 2.3 Place canals on the map

In [321]:
# VV is a matrix with this shape: number of nodes by number of nodes
len_level_0 = len_vertical, len_horizontal
# Initialize the empty VV
level_0 = np.zeros(len_level_0, dtype=int)

# Iterate over the egdes.
for n1, n2 in water:
    level_0[n1, n2] = 1 # Water pixels are shown as 1

# display as pandas dataframe
map_display = display(pd.DataFrame(level_0))
map_display

0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4    0   0   0   0   0   1   1   1   1   1  ...   0   0   0   0   0   0   0   
5    0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
6    0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
7    0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
8    0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
9    0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
10   0   0   0   0   0   1   1   1   1   1  ...   1   1   1   1   1   1   1   
11   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
12   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
13   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   

    21  22  23  
0    0   0   0  
1    0   0   0  
2    0   0   0  
3    0   0   0  
4    0   0   0  
5    0   0   0  
6    0   0   0  
7    0   0   0  
8    0   0   0  
9    0   0   0  
10   1   1   1  
11   0   0   0  
12   0   0   0  
13   0   0   0  

[14 rows x 24 columns]

# 3. Merchant roads

## 3.1 Find row and column with most water

In [322]:
# Find the row and column with the most water
canal_row = level_0.sum(axis=1).argmax()
canal_column = np.argmax(np.max(level_0, axis=0))

# Count the amount of water modules
water_modules_in_row = np.count_nonzero(level_0[canal_row])
water_modules_in_column = np.count_nonzero(level_0[:,canal_column])

print("Max water row:",canal_row, "Max water column:", canal_column)
print("Water modules in row:", water_modules_in_row, ". Water modules in column:", water_modules_in_column)

Max water row: 10 Max water column: 5
Water modules in row: 19 . Water modules in column: 10


## 3.2 Find row and column most central

In [323]:
# Find the row and column that are most central
central_row = int(len_vertical // 2)
central_column = int(len_horizontal // 2)

print("The central row is:", central_row, "The central column is:", central_column)


The central row is: 7 The central column is: 12


## 3.3.1 Horizontal road

In [324]:
# Potential rows where the roads can be placed
row_above = canal_row -1
row_below = canal_row + 1

potential_roads_horizontal = [row_above,row_below]
print("The potential rows are:", potential_roads_horizontal)

# Function for picking the right one
def find_nearest(potential_roads_horizontal, central_row):
    array = np.asarray(potential_roads_horizontal)
    idx = (np.abs(array - central_row)).argmin(0)
    return array[idx]

# Call function
horizontal_road = find_nearest(potential_roads_horizontal, central_row)

print("Horizontal road:", horizontal_road)

The potential rows are: [9, 11]
Horizontal road: 9


## 3.3.2 Horizontal road

In [325]:
# Potential columns where the roads can be placed
column_above = canal_column -1
column_below = canal_column + 1

potential_roads_vertical = [column_above,column_below]
print("The potential columns are:", potential_roads_vertical)

# Function for picking the right one
def find_nearest(potential_roads_vertical, central_column):
    array = np.asarray(potential_roads_vertical)
    idx = (np.abs(array - central_column)).argmin(0)
    return array[idx]

# Call function
vertical_road = find_nearest(potential_roads_vertical, central_column)

print("vertical road:", vertical_road)

The potential columns are: [4, 6]
vertical road: 6


## 3.4 Plot roads on map

In [326]:
# Plot roads on the grid
level_0[ horizontal_road, : ] = [2]
level_0[ :, vertical_road ] = [2]

print(level_0)


[[0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [0 0 0 0 0 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


## 3.5 List of the coordinates of road

In [327]:
# Make a list of merchant roads. The output is used when going to a 3D matrix (distinct between floors)
roads_list = np.argwhere(level_0 == 2)
roads_list

array([[ 0,  6],
       [ 1,  6],
       [ 2,  6],
       [ 3,  6],
       [ 4,  6],
       [ 5,  6],
       [ 6,  6],
       [ 7,  6],
       [ 8,  6],
       [ 9,  0],
       [ 9,  1],
       [ 9,  2],
       [ 9,  3],
       [ 9,  4],
       [ 9,  5],
       [ 9,  6],
       [ 9,  7],
       [ 9,  8],
       [ 9,  9],
       [ 9, 10],
       [ 9, 11],
       [ 9, 12],
       [ 9, 13],
       [ 9, 14],
       [ 9, 15],
       [ 9, 16],
       [ 9, 17],
       [ 9, 18],
       [ 9, 19],
       [ 9, 20],
       [ 9, 21],
       [ 9, 22],
       [ 9, 23],
       [10,  6],
       [11,  6],
       [12,  6],
       [13,  6]], dtype=int64)

# 4. Sub-roads

## 4.1 Define sub-roads and plot on map

In [328]:
# Define distance between roads
distance_between_roads = 6

# Find the location of the sub-roads
sub_roads = np.arange(start=vertical_road, stop=len_horizontal, step=distance_between_roads)

# Place the sub-roads in the grid
level_0[:, sub_roads] = [2]

print (level_0)

[[0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 1 1 1 1 1 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [0 0 0 0 0 1 2 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]]


## 4.1 List of the coordinates of roads and sub-roads

In [329]:
# Make a list of sub-roads. The output is used when going to a 3D matrix (distinct between floors)
sub_roads_list = np.argwhere(level_0 == 2)
sub_roads_list

array([[ 0,  6],
       [ 0, 12],
       [ 0, 18],
       [ 1,  6],
       [ 1, 12],
       [ 1, 18],
       [ 2,  6],
       [ 2, 12],
       [ 2, 18],
       [ 3,  6],
       [ 3, 12],
       [ 3, 18],
       [ 4,  6],
       [ 4, 12],
       [ 4, 18],
       [ 5,  6],
       [ 5, 12],
       [ 5, 18],
       [ 6,  6],
       [ 6, 12],
       [ 6, 18],
       [ 7,  6],
       [ 7, 12],
       [ 7, 18],
       [ 8,  6],
       [ 8, 12],
       [ 8, 18],
       [ 9,  0],
       [ 9,  1],
       [ 9,  2],
       [ 9,  3],
       [ 9,  4],
       [ 9,  5],
       [ 9,  6],
       [ 9,  7],
       [ 9,  8],
       [ 9,  9],
       [ 9, 10],
       [ 9, 11],
       [ 9, 12],
       [ 9, 13],
       [ 9, 14],
       [ 9, 15],
       [ 9, 16],
       [ 9, 17],
       [ 9, 18],
       [ 9, 19],
       [ 9, 20],
       [ 9, 21],
       [ 9, 22],
       [ 9, 23],
       [10,  6],
       [10, 12],
       [10, 18],
       [11,  6],
       [11, 12],
       [11, 18],
       [12,  6],
       [12, 12

## 5.1 Possible places for well

In [330]:
# Make a list of all coordinates where a well can be placed. This means finding the water modules
potential_wells = np.argwhere(level_0 == 1)

# Function that makes tuples that can be used to place wells on the grid
def make_tuples(a):
    try:
        return tuple(make_tuples(i) for i in a)
    except TypeError:
        return a

# Run the function with the potential well spots
potential_wells_list = list(make_tuples(potential_wells))

# Define the starting point of the wells and define the distance
start = 3
distance = 5

# Find and replace water with wells
for i in range(start,len(potential_wells_list),distance):
    if level_0[potential_wells_list[i][0],potential_wells_list[i][1]] == 1:
        level_0[potential_wells_list[i][0],potential_wells_list[i][1]] = 5

for row in level_0:
    print(row)

[0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 1 2 1 1 5 1 1 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 5 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 1 2 1 1 5 1 1 2 1 1 5 1 1 2 1 1 5 1 1]
[0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 1 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 5 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0]


## 5.2 List of coordinates of wells

In [331]:
# Make a list of wells. The output is used when going to a 3D matrix (distinct between floors)
wells = np.argwhere(level_0 == 5)
wells

array([[ 4,  9],
       [ 7,  5],
       [10,  9],
       [10, 15],
       [10, 21],
       [13,  5]], dtype=int64)